on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install terraform
      uses: hashicorp/setup-terraform@v3
    - name: terraform validate
      run: | 
        terraform --version
    - name: terraform init
      run: | 
        cd ${{ github.workspace }}/learn-terraform-aws-instance/local_state/
        terraform init
        terraform plan
        
          
      
  
